# Site settings
title: Qiuwen Chen
email: qchen14 (at) syr (dot) edu
description: > # this means to ignore newlines until "baseurl:"
  Personal landing page, blogs and conveniences
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: autchen

# Build settings
markdown: kramdown
